-- Add session_summary column to conversations table
ALTER TABLE conversations 
ADD COLUMN IF NOT EXISTS session_summary JSONB DEFAULT NULL;

-- Comment on column
COMMENT ON COLUMN conversations.session_summary IS 'Rolling session summary generated by AI: {summary, topics, last_run_id}';
