export const SILICONFLOW_BASE_URL = 'https://api.siliconflow.cn/v1'
export const GLM_BASE_URL = 'https://open.bigmodel.cn/api/paas/v4'
export const MODELSCOPE_BASE_URL = 'https://api-inference.modelscope.cn/v1'
// export const KIMI_BASE_URL = 'https://api.moonshot.cn/v1'
export const NVIDIA_BASE_URL = 'https://integrate.api.nvidia.com/v1'
export const MINIMAX_BASE_URL = 'https://api.minimax.io/v1'
