export const TOOL_TRANSLATION_KEYS = {
  Tavily_web_search: 'tools.webSearch',
  Tavily_academic_search: 'tools.academicSearch',
  calculator: 'tools.calculator',
  local_time: 'tools.localTime',
  summarize_text: 'tools.summarizeText',
  extract_text: 'tools.extractText',
  json_repair: 'tools.jsonRepair',
  interactive_form: 'tools.interactiveForm',
  webpage_reader: 'tools.webpageReader',
  document_embedding: 'tools.documentEmbedding',
  memory_check: 'tools.memoryCheck',
  web_search_using_tavily: 'tools.tavilyWebSearch',
  web_search_with_tavily: 'tools.tavilySearchContext',
  extract_url_content: 'tools.tavilyExtract',
  web_search: 'tools.ddgWebSearch',
  search_news: 'tools.ddgNewsSearch',
  search_arxiv_and_return_articles: 'tools.arxivSearch',
  read_arxiv_papers: 'tools.arxivRead',
  search_wikipedia: 'tools.wikipediaSearch',
  get_current_stock_price: 'tools.stockPrice',
  get_company_info: 'tools.companyInfo',
  get_stock_fundamentals: 'tools.stockFundamentals',
  get_income_statements: 'tools.incomeStatements',
  get_key_financial_ratios: 'tools.financialRatios',
  get_analyst_recommendations: 'tools.analystRecommendations',
  get_company_news: 'tools.companyNews',
  get_technical_indicators: 'tools.technicalIndicators',
  get_historical_stock_prices: 'tools.historicalPrices',
}

// Tool icons mapping (using lucide-react icon names)
export const TOOL_ICONS = {
  Tavily_web_search: 'Search',
  Tavily_academic_search: 'GraduationCap',
  calculator: 'Calculator',
  local_time: 'Clock',
  summarize_text: 'FileText',
  extract_text: 'ScanText',
  json_repair: 'Wrench',
  interactive_form: 'FormInput',
  webpage_reader: 'Globe',
  document_embedding: 'ScanText',
  memory_check: 'Brain',
  web_search_using_tavily: 'Search',
  web_search_with_tavily: 'Search',
  extract_url_content: 'Globe',
  web_search: 'Search',
  search_news: 'Search',
  search_arxiv_and_return_articles: 'GraduationCap',
  read_arxiv_papers: 'FileText',
  search_wikipedia: 'Globe',
  get_current_stock_price: 'LineChart',
  get_company_info: 'FileText',
  get_stock_fundamentals: 'LineChart',
  get_income_statements: 'FileText',
  get_key_financial_ratios: 'LineChart',
  get_analyst_recommendations: 'LineChart',
  get_company_news: 'Search',
  get_technical_indicators: 'LineChart',
  get_historical_stock_prices: 'LineChart',
}

// Tool usage info keys for translations
export const TOOL_INFO_KEYS = {
  Tavily_web_search: 'tools.webSearchInfo',
  Tavily_academic_search: 'tools.academicSearchInfo',
  calculator: 'tools.calculatorInfo',
  local_time: 'tools.localTimeInfo',
  summarize_text: 'tools.summarizeTextInfo',
  extract_text: 'tools.extractTextInfo',
  json_repair: 'tools.jsonRepairInfo',
  interactive_form: 'tools.interactiveFormInfo',
  webpage_reader: 'tools.webpageReaderInfo',
  document_embedding: 'tools.documentEmbeddingInfo',
  memory_check: 'tools.memoryCheckInfo',
  web_search_using_tavily: 'tools.tavilyWebSearchInfo',
  web_search_with_tavily: 'tools.tavilySearchContextInfo',
  extract_url_content: 'tools.tavilyExtractInfo',
  web_search: 'tools.ddgWebSearchInfo',
  search_news: 'tools.ddgNewsSearchInfo',
  search_arxiv_and_return_articles: 'tools.arxivSearchInfo',
  read_arxiv_papers: 'tools.arxivReadInfo',
  search_wikipedia: 'tools.wikipediaSearchInfo',
  get_current_stock_price: 'tools.stockPriceInfo',
  get_company_info: 'tools.companyInfoInfo',
  get_stock_fundamentals: 'tools.stockFundamentalsInfo',
  get_income_statements: 'tools.incomeStatementsInfo',
  get_key_financial_ratios: 'tools.financialRatiosInfo',
  get_analyst_recommendations: 'tools.analystRecommendationsInfo',
  get_company_news: 'tools.companyNewsInfo',
  get_technical_indicators: 'tools.technicalIndicatorsInfo',
  get_historical_stock_prices: 'tools.historicalPricesInfo',
}
