export const DOCUMENT_RETRIEVAL_CHUNK_LIMIT = 250
export const DOCUMENT_RETRIEVAL_TOP_CHUNKS = 5
export const QUERY_CONTEXT_MAX_CHARS = 1200
export const QUERY_HISTORY_MAX_MESSAGES = 6
export const MEMORY_DOMAIN_PROMPT_LIMIT = 20
